octokit/routes

README.md
lib/endpoint/find-parameters.js
package.json

rename to @octokit/routes

---

README.md

Wow GitHub pages has never been that useful before

Add JSON download links to README

---

index.json
lib/endpoint/find-routes.js
lib/endpoint/tags/div.alert.note.js
lib/endpoint/tags/div.alert.tip.js
lib/endpoint/tags/div.alert.warning.js
routes/gists.json
routes/gists/list-public-gists-for-the-specified-user.json
routes/gists/list-the-authenticated-users-gists-or-if-called-anonymously-this-will-return-all-public-gists.json
routes/git.json
routes/git/refs/delete-a-reference.json
routes/repos.json
routes/repos/commits/compare-two-commits.json
routes/repos/create-a-new-repository-for-the-authenticated-user.json
routes/repos/create-a-new-repository-in-this-organization.json
routes/scim.json
routes/scim/get-a-list-of-provisioned-identities.json

Adds missing routes

---

index.json
lib/endpoint/tags/table.js
routes/repos.json
routes/repos/create-a-new-repository-for-the-authenticated-user.json
routes/repos/create-a-new-repository-in-this-organization.json
routes/repos/edit.json

WIP Repositories - Create: enum[true, false] should be boolean

---

index.json
lib/endpoint/find-parameters.js
routes/activity.json
routes/activity/events/list-events-for-an-organization.json
routes/activity/events/list-events-performed-by-a-user.json
routes/activity/events/list-events-that-a-user-has-received.json
routes/activity/events/list-issue-events-for-a-repository.json
routes/activity/events/list-public-events-for-a-network-of-repositories.json
routes/activity/events/list-public-events-for-an-organization.json
routes/activity/events/list-public-events-performed-by-a-user.json
routes/activity/events/list-public-events-that-a-user-has-received.json
routes/activity/events/list-public-events.json
routes/activity/events/list-repository-events.json
routes/repos.json
routes/repos/list-user-repositories.json
routes/repos/list-your-repositories.json

add pagination headers to endpoints without response example but with names starting with "List ..."

---

index.json
lib/endpoint/find-parameters.js
lib/endpoint/get.js
lib/endpoint/tags/table.js
routes/git.json
routes/git/trees/create-a-tree.json
routes/pulls.json
routes/pulls/reviews/create-a-pull-request-review.json

fixes https://github.com/octokit/routes/issues/58, fixes #69, fixes https://github.com/octokit/routes/issues/60

"comments" parameter type should be "objects[]"

---

index.json
lib/endpoint/find-parameters.js
routes/activity.json
routes/activity/notifications/list-your-notifications-in-a-repository.json
routes/activity/notifications/list-your-notifications.json
routes/activity/notifications/mark-as-read.json
routes/activity/notifications/mark-notifications-as-read-in-a-repository.json

Replaced Time.now with <current date/time>

---

index.json
lib/endpoint/tags/table.js
routes/git.json
routes/git/tags/create-a-tag-object.json
routes/orgs.json
routes/orgs/edit-an-organization.json
routes/orgs/members/edit-your-organization-membership.json
routes/reactions.json
routes/reactions/create-reaction-for-a-commit-comment.json
routes/reactions/create-reaction-for-a-pull-request-review-comment.json
routes/reactions/create-reaction-for-a-team-discussion-comment.json
routes/reactions/create-reaction-for-a-team-discussion.json
routes/reactions/create-reaction-for-an-issue-comment.json
routes/reactions/create-reaction-for-an-issue.json
routes/reactions/list-reactions-for-a-commit-comment.json
routes/reactions/list-reactions-for-a-pull-request-review-comment.json
routes/reactions/list-reactions-for-a-team-discussion-comment.json
routes/reactions/list-reactions-for-a-team-discussion.json
routes/reactions/list-reactions-for-an-issue-comment.json
routes/reactions/list-reactions-for-an-issue.json
routes/teams.json
routes/teams/create-team.json

closes #94, #95, #96, #98 and #99  .

Multiple Issue Fix.

---

index.json
lib/endpoint/tags/table.js
routes/issues.json
routes/issues/list-issues-for-a-repository.json

Fix: List issues for a repository: parameter type "integer or string" should be "string"

---

index.json
lib/endpoint/tags/table.js
routes/migration.json
routes/migration/source-imports/start-an-import.json

Fix: Migration - Start an import: parameter type "url" should be "string"

---

index.json
lib/endpoint/find-parameters.js
routes/repos.json
routes/repos/branches/update-branch-protection.json
routes/repos/branches/update-pull-request-review-enforcement-of-protected-branch.json

Fix: Repos: Update branch protection: `dismissal_restrictions.*` should be `required_pull_request_reviews .dismissal_restrictions.*`

---

index.json
lib/endpoint/find-parameters.js
routes/repos.json
routes/repos/branches/update-pull-request-review-enforcement-of-protected-branch.json

see https://github.com/octokit/routes/pull/110/files#r184120778

fix regression from #110

---

index.json
lib/endpoint/find-parameters.js
lib/endpoint/overrides/routes.js
routes/git.json
routes/git/trees/create-a-tree.json
routes/pulls.json
routes/pulls/reviews/create-a-pull-request-review.json
routes/scim.json
routes/scim/get-a-list-of-provisioned-identities.json

Object array item parameter notation

---

index.json
lib/endpoint/find-parameters.js
routes/checks.json
routes/checks/runs/create-a-check-run.json
routes/checks/runs/update-a-check-run.json
routes/repos.json
routes/repos/branches/update-branch-protection.json

Checks: annotations parameters

---

lib/endpoint/to-id-name.js

remove workaround for organization migrations

---

index.json
lib/endpoint/tags/table.js
routes/projects.json
routes/projects/cards/move-a-project-card.json
routes/projects/columns/move-a-project-column.json

turn enum values with placeholders into regex

---

index.json
lib/endpoint/find-parameters.js
lib/endpoint/overrides/map-parameters-to-input.js
lib/endpoint/overrides/v3/repos/releases/upload-a-release-asset.json
routes/issues.json
routes/issues/labels/add-labels-to-an-issue.json
routes/issues/labels/replace-all-labels-for-an-issue.json
routes/markdown.json
routes/markdown/render-a-markdown-document-in-raw-mode.json
routes/repos.json
routes/repos/branches/add-required-status-checks-contexts-of-protected-branch.json
routes/repos/branches/add-team-restrictions-of-protected-branch.json
routes/repos/branches/add-user-restrictions-of-protected-branch.json
routes/repos/branches/remove-required-status-checks-contexts-of-protected-branch.json
routes/repos/branches/remove-team-restrictions-of-protected-branch.json
routes/repos/branches/remove-user-restrictions-of-protected-branch.json
routes/repos/branches/replace-required-status-checks-contexts-of-protected-branch.json
routes/repos/branches/replace-team-restrictions-of-protected-branch.json
routes/repos/branches/replace-user-restrictions-of-protected-branch.json
routes/repos/releases/upload-a-release-asset.json

Add flag for parameters that is expected to be sent as request body root

---

index.json
lib/endpoint/html-to-json.js
lib/endpoint/overrides/workarounds.js
lib/endpoint/tags/h1-or-h2.js
lib/endpoint/tags/table.js
routes/checks.json
routes/checks/runs/create-a-check-run.json
routes/checks/runs/update-a-check-run.json
routes/repos.json
routes/repos/deployments/create-a-deployment-status.json

enum values fixed for "Create/Update a Check Run" and "Create a Deployment Status

---

index.json
lib/endpoint/html-to-json.js
lib/endpoint/overrides/workarounds.js
lib/endpoint/tags/h1-or-h2.js
lib/endpoint/tags/table.js
routes/checks.json
routes/checks/runs/create-a-check-run.json
routes/checks/runs/update-a-check-run.json
routes/pulls.json
routes/pulls/comments/create-a-comment-reply.json
routes/pulls/create-a-pull-request-from-an-issue.json
routes/repos.json
routes/repos/deployments/create-a-deployment-status.json

better names to secondary routes found in same docs section

---

index.json
lib/endpoint/tags/table.js
routes/pulls.json
routes/pulls/reviews/create-a-pull-request-review.json
routes/pulls/reviews/dismiss-a-pull-request-review.json
routes/pulls/reviews/submit-a-pull-request-review.json

message parameter is required for "Dismiss a Pull Request Review" route

---

index.json
lib/endpoint/find-parameters.js
routes/repos.json
routes/repos/contents/create-a-file.json
routes/repos/contents/update-a-file.json

committer.name/email parameters added to creat/update a file

---

bin/octokit-rest-routes.js

exit with non-zero on exit

---

index.json
lib/endpoint/add-triggers-notification-flag.js
lib/endpoint/html-to-json.js
routes/issues.json
routes/issues/comments/create-a-comment.json
routes/issues/create-an-issue.json
routes/pulls.json
routes/pulls/comments/create-a-comment-reply.json
routes/pulls/comments/create-a-comment.json
routes/pulls/create-a-pull-request-from-an-issue.json
routes/pulls/create-a-pull-request.json
routes/pulls/merge-a-pull-request-merge-button.json
routes/pulls/review-requests/create-a-review-request.json
routes/repos.json
routes/repos/comments/create-a-commit-comment.json
routes/repos/releases/create-a-release.json
routes/teams.json
routes/teams/discussion-comments/create-a-comment.json

triggers notification

---

README.md

closes #162
-----
[View rendered README.md](https://github.com/octokit/routes/blob/gr2m-patch-1/README.md)

Link to package manager pages

---

lib/endpoint/overrides/workarounds.js
routes/ghe-2.13/index.json
routes/ghe-2.13/issues.json
routes/ghe-2.13/issues/replace-labels.json
routes/ghe-2.14/index.json
routes/ghe-2.14/issues.json
routes/ghe-2.14/issues/replace-labels.json
routes/ghe-2.15/index.json
routes/ghe-2.15/issues.json
routes/ghe-2.15/issues/replace-labels.json

thanks @tknickman! Closes #332

add workaround to `issues.replaceLabels` to GHE <= 2.15

---

lib/endpoint/tags/table.js
routes/api.github.com/index.json
routes/api.github.com/repos.json
routes/api.github.com/repos/list.json
routes/ghe-2.13/index.json
routes/ghe-2.13/repos.json
routes/ghe-2.13/repos/list.json
routes/ghe-2.14/index.json
routes/ghe-2.14/repos.json
routes/ghe-2.14/repos/list.json
routes/ghe-2.15/index.json
routes/ghe-2.15/repos.json
routes/ghe-2.15/repos/list.json
routes/ghe-2.16/index.json
routes/ghe-2.16/repos.json
routes/ghe-2.16/repos/list.json

closes #297, ref https://github.com/octokit/routes/issues/297

List your repositories: "affiliation" parameter is not an enum

---

package.json

Update tap to version 13.0.3

---

lib/endpoint/tags/table.js
routes/api.github.com/index.json
routes/api.github.com/repos.json
routes/api.github.com/repos/enable-pages-site.json

Enable a Pages site: source[path] & source[branch] params should follow "source.path" notion

---

lib/endpoint/find-parameters.js
routes/api.github.com/index.json
routes/api.github.com/repos.json
routes/api.github.com/repos/delete-file.json
routes/ghe-2.14/index.json
routes/ghe-2.14/repos.json
routes/ghe-2.14/repos/delete-file.json
routes/ghe-2.15/index.json
routes/ghe-2.15/repos.json
routes/ghe-2.15/repos/delete-file.json
routes/ghe-2.16/index.json
routes/ghe-2.16/repos.json
routes/ghe-2.16/repos/delete-file.json
routes/ghe-2.17/index.json
routes/ghe-2.17/repos.json
routes/ghe-2.17/repos/delete-file.json

+ incidentally clean up the description too
fixes #426

fix: pick up author/committer properties in optional header block (#426)

---

.github/main.workflow

closes https://github.com/octokit/routes/issues/438

fix cron job

---

.github/main.workflow
package-lock.json
package.json

Don’t test before deploying. The testing should have happened on other branches before merging anyway.
The problem is that `npm ci` gets canceled and sets the state to error in the deploy workflow, because `master branch only` exits with `neutral`
fixes #474

Fix deploy workflow

---

package.json

Publish both the openapi and lib folder to npm

---

lib/endpoint/overrides/deprecations.js
lib/openapi.js
openapi/api.github.com/operations/repos/get-commit.json
openapi/ghe-2.15/operations/repos/get-commit.json
openapi/ghe-2.16/operations/repos/get-commit.json
openapi/ghe-2.17/operations/repos/get-commit.json
package-lock.json
package.json

There were a few problems with missing dependencies and some code problems that are resolved via this pull request

fix node usage

---

README.md
lib/check-or-update-routes.js
lib/endpoint/tags/p.js
lib/endpoint/tags/ul.js
test/integration/landing-page-test.js

-----
[View rendered README.md](https://github.com/octokit/routes/blob/gr2m-patch-1/README.md)

docs(README): add nightly update status badge

---

README.md
lib/endpoint/overrides/v3/git/refs/get-a-reference.json
lib/endpoint/overrides/v3/git/refs/get-all-references.json
lib/endpoint/overrides/v3/git/trees/get-a-tree.json
lib/endpoint/overrides/v3/repos/releases/upload-a-release-asset.json
openapi/api.github.com/operations/git/get-ref.json
openapi/api.github.com/operations/git/get-tree.json
openapi/ghe-2.15/operations/git/get-ref.json
openapi/ghe-2.15/operations/git/get-tree.json
openapi/ghe-2.16/operations/git/get-ref.json
openapi/ghe-2.16/operations/git/get-tree.json
openapi/ghe-2.17/operations/git/get-ref.json
openapi/ghe-2.17/operations/git/get-tree.json
openapi/ghe-2.18/operations/git/get-ref.json
openapi/ghe-2.18/operations/git/get-tree.json

Continues fix started in https://github.com/octokit/routes/pull/513
-----
[View rendered README.md](https://github.com/Redocly/routes/blob/fix/server-url-in-overlays/README.md)

fix: shell samples URLs in overlays

---

lib/endpoint/overrides/v3/git/trees/get-a-tree.json
openapi/api.github.com/operations/git/get-tree.json
openapi/ghe-2.15/operations/git/get-tree.json
openapi/ghe-2.16/operations/git/get-tree.json
openapi/ghe-2.17/operations/git/get-tree.json
openapi/ghe-2.18/operations/git/get-tree.json

looks like it was removed accidentally

"recursive" parameter for "Get a tree" endpoint

---

.github/workflows/update.yml

Update an existing pull request instead of creating a new one

Run routes update cron job hourly

---

lib/endpoint/overrides/deprecations.js
openapi/api.github.com/operations/teams/remove-membership-legacy.json

addresses https://github.com/octokit/rest.js/issues/1553

add deprecation to teams/remove-membership-legacy

---

bin/run-tests.js
cache/api.github.com/v3/repos/releases/upload-a-release-asset.html
lib/check-or-update-routes.js
lib/endpoint/get.js
lib/endpoint/overrides/v3/repos/releases/upload-a-release-asset.json
openapi/api.github.com/index.json
openapi/api.github.com/operations/repos/upload-release-asset.json
openapi/ghe-2.16/index.json
openapi/ghe-2.16/operations/git/get-refs.json
openapi/ghe-2.16/operations/repos/upload-release-asset.json
openapi/ghe-2.17/index.json
openapi/ghe-2.17/operations/git/get-refs.json
openapi/ghe-2.17/operations/repos/upload-release-asset.json
openapi/ghe-2.18/index.json
openapi/ghe-2.18/operations/git/get-refs.json
openapi/ghe-2.18/operations/repos/upload-release-asset.json
openapi/ghe-2.19/index.json
openapi/ghe-2.19/operations/repos/upload-release-asset.json

Upload a release asset

---

openapi/api.github.com/index.json

Update OpenAPI info.description

---

lib/endpoint/overrides/workarounds.js
openapi/api.github.com/operations/gists/fork.json
openapi/api.github.com/operations/gists/update.json
openapi/ghe-2.17/operations/gists/fork.json
openapi/ghe-2.17/operations/gists/update.json
openapi/ghe-2.18/operations/gists/fork.json
openapi/ghe-2.18/operations/gists/update.json
openapi/ghe-2.19/operations/gists/fork.json
openapi/ghe-2.19/operations/gists/update.json
openapi/ghe-2.20/operations/gists/fork.json
openapi/ghe-2.20/operations/gists/update.json

Update to https://github.com/octokit/routes/pull/723

fix: fix files schema for the remaining gists

---

lib/endpoint/overrides/deprecations.js
openapi/api.github.com/operations/actions/download-job-logs-for-workflow-run.json
openapi/api.github.com/operations/actions/get-job-for-workflow-run.json
openapi/api.github.com/operations/apps/create-installation-access-token.json
openapi/api.github.com/operations/apps/list-repos-accessible-to-installation.json
openapi/api.github.com/operations/apps/revoke-installation-access-token.json
openapi/api.github.com/operations/interactions/set-restrictions-for-org.json
openapi/api.github.com/operations/interactions/set-restrictions-for-repo.json
openapi/ghe-2.18/operations/apps/create-installation-access-token.json
openapi/ghe-2.18/operations/apps/list-repos-accessible-to-installation.json
openapi/ghe-2.19/operations/apps/create-installation-access-token.json
openapi/ghe-2.19/operations/apps/list-repos-accessible-to-installation.json
openapi/ghe-2.20/operations/apps/create-installation-access-token.json
openapi/ghe-2.20/operations/apps/list-repos-accessible-to-installation.json
openapi/ghe-2.20/operations/apps/revoke-installation-access-token.json

addresses https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/124

fix: add missing deprecations
